---
version: "3.9"

services:
  backend:
    container_name: note_backend
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@note_db:5432/postgres
    depends_on:
      - note_db

  note_db:
    container_name: note_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
